# Generated by Django 4.2.2 on 2023-06-27 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=62)),
                ('surname', models.CharField(max_length=62)),
                ('parent_name', models.CharField(max_length=62)),
                ('article_counter', models.PositiveIntegerField(default=0)),
                ('speciality', models.CharField(max_length=128)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=128)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='mainapp.author')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('visitors_counter', models.PositiveIntegerField()),
            ],
        ),
    ]
