# Generated by Django 4.2.2 on 2023-07-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=62, verbose_name='фамилия')),
                ('name', models.CharField(max_length=62, verbose_name='имя')),
                ('parent_name', models.CharField(blank=True, max_length=62, verbose_name='отчество')),
                ('article_counter', models.PositiveIntegerField(default=0, verbose_name='количество статей')),
                ('speciality', models.CharField(max_length=128, verbose_name='специальность')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
            ],
            options={
                'verbose_name': 'автор',
                'verbose_name_plural': 'авторы',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('category', models.CharField(max_length=128, verbose_name='категория')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='изображение')),
                ('text', models.TextField(default='', verbose_name='текст статьи')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='дата сознания')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('visitors_counter', models.PositiveIntegerField(default=0, verbose_name='количество просмотров')),
                ('is_published', models.BooleanField(default=False, verbose_name='публикация на сайте')),
                ('author', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='mainapp.author', verbose_name='автор')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ['category'],
            },
        ),
    ]
