# Generated by Django 4.2.2 on 2023-06-29 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['category'], 'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['surname'], 'verbose_name': 'автор', 'verbose_name_plural': 'авторы'},
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(default='', verbose_name='текст статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='mainapp.author', verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(max_length=128, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата сознания'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='дата обновления'),
        ),
        migrations.AlterField(
            model_name='article',
            name='visitors_counter',
            field=models.PositiveIntegerField(verbose_name='количество просмотров'),
        ),
        migrations.AlterField(
            model_name='author',
            name='article_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='количество статей'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=62, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='parent_name',
            field=models.CharField(blank=True, max_length=62, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='author',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='author',
            name='speciality',
            field=models.CharField(max_length=128, verbose_name='специальность'),
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(max_length=62, verbose_name='фамилия'),
        ),
    ]
