# Generated by Django 4.2.2 on 2023-06-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_article_options_alter_author_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='публикация на сайте'),
        ),
        migrations.AlterField(
            model_name='article',
            name='visitors_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
